name: mynas_backend
description: Backend server for MyNAS Manager
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_cors_headers: ^0.1.5
  shelf_web_socket: ^2.0.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  dio: ^5.7.0
  args: ^2.6.0
  logging: ^1.3.0
  dotenv: ^4.2.0
  mynas_shared:
    path: ../shared

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  shelf_hotreload: ^1.4.1
