name: mynas_shared
description: Shared models and utilities for MyNAS Manager
version: 1.0.0
license: AGPL-3.0

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
